# This workflow will run tests for the downloads and online readings collections
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Downloads Tests CI

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: fisbookBE-downloads

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          MONGO_URI_DOWNLOADS_TEST: ${{ secrets.MONGO_URI_DOWNLOADS_TEST }}

  integration:
    needs: test

    runs-on: ubuntu-latest
    environment: fisbookBE-downloads

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: echo $MONGO_URI_DOWNLOADS_TEST
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run integration
        env:
          MONGO_URI_DOWNLOADS_TEST: ${{ secrets.MONGO_URI_DOWNLOADS_TEST }}